// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path"
import { fileURLToPath } from "node:url"
import { defineConfig } from "prisma/config"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const dbUrl = `file:${path.join(__dirname, "prisma/dev.db")}`

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
})
